# Generated by Django 5.1.7 on 2025-05-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/network/images/penguin.png', null=True, upload_to='profile_pics/'),
        ),
    ]
