# Generated by Django 5.1.7 on 2025-05-03 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
